/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf 
Author: LarsH. (https://sketchfab.com/LarsH.)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/imperial-i-class-star-destroyer-6913bf20402a4eaea3e59109db0fbea4
Title: Imperial I-Class Star Destroyer
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/LOWRESimperial_i-class_star_destroyer.glb");
  return (
    <group {...props} dispose={null} scale={[3.5, 3.5, 3.5]}>
      <group rotation={[-Math.PI / 1, 3, 1]}>
        <group rotation={[Math.PI / 2, 1, 1]}>
          <mesh
            geometry={nodes.defaultMaterial.geometry}
            material={materials.StarDestroyer_BasicHull}
          />
          <mesh
            geometry={nodes.defaultMaterial_1.geometry}
            material={materials.StarDestroyer_FineDetails}
          />
          <mesh
            geometry={nodes.defaultMaterial_2.geometry}
            material={materials.StarDestroyer_FineDetails}
          />
          <mesh
            geometry={nodes.defaultMaterial_3.geometry}
            material={materials.StarDestroyer_FineDetails}
          />
          <mesh
            geometry={nodes.defaultMaterial_4.geometry}
            material={materials.StarDestroyer_FineDetails}
          />
          <mesh
            geometry={nodes.defaultMaterial_5.geometry}
            material={materials.StarDestroyer_BasicDetails}
          />
          <mesh
            geometry={nodes.defaultMaterial_6.geometry}
            material={materials.StarDestroyer_Turbolaser}
          />
          <mesh
            geometry={nodes.defaultMaterial_7.geometry}
            material={materials.StarDestroyer_Turbolaser}
          />
          <mesh
            geometry={nodes.defaultMaterial_8.geometry}
            material={materials.StarDestroyer_Turbolaser}
          />
          <mesh
            geometry={nodes.defaultMaterial_9.geometry}
            material={materials.StarDestroyer_Turbolaser}
          />
          <mesh
            geometry={nodes.defaultMaterial_10.geometry}
            material={materials.StarDestroyer_Turbolaser}
          />
          <mesh
            geometry={nodes.defaultMaterial_11.geometry}
            material={materials.StarDestroyer_Turbolaser}
          />
          <mesh
            geometry={nodes.defaultMaterial_12.geometry}
            material={materials.StarDestroyer_Turbolaser}
          />
          <mesh
            geometry={nodes.defaultMaterial_13.geometry}
            material={materials.StarDestroyer_Turbolaser}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/LOWRESimperial_i-class_star_destroyer.glb");
